# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://dttngan91.github.io"
title: Ngan Do developer 
theme: jekyll-theme-cayman
description: Enjoy game of life!
social-network-links:
  rss: true
  email: "dttngan91@gmail.com"
  facebook: ngan.tuyet.3
  github: dttngan91 
  twitter: ngando_foxy
avatar: "avatar_official.png"
show_downloads: false 
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
link-tags: true
author:
  name: Ngan Do 
